name: flutter_weather_demo
description: A new Flutter project.
environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.1.0
  http: "^0.11.3+16"
  rxdart: ^0.20.0
  rx_command: any
#    path: ..\

dev_dependencies:
  build_runner: ^0.10.1+1
  json_serializable: ^1.1.0

flutter:
  uses-material-design: true
