name: rx_command
description: Reactive event handler wrapper class inspired by ReactiveUI.
version: 6.0.0-null-safety.1
maintainer: Thomas Burkhart (@escamoteur)
authors:
  - Flutter Community <community@flutter.zone>
  - Thomas Burkhart <burkhartsengineering@gmail.com>
homepage: https://github.com/fluttercommunity/rx_command
documentation:
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.26.0
  quiver: ^3.0.1


dev_dependencies:
  test: any

